name: MuscleMap
options:
  bundleIdPrefix: com.buildinpublic
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"
  generateEmptyDirectories: true

packages:
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios-spm.git
    majorVersion: 5.0.0

targets:
  MuscleMap:
    type: application
    platform: iOS
    sources:
      - path: MuscleMap
        excludes:
          - "**/.DS_Store"
      - path: Resources
        buildPhase: resources
    dependencies:
      - package: RevenueCat
        product: RevenueCat
      - target: MuscleMapWidgetExtension
    entitlements:
      path: MuscleMap/MuscleMap.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.buildinpublic.MuscleMap
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.buildinpublic.MuscleMap
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        INFOPLIST_GENERATION_ENABLED: true
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_CFBundleDisplayName: "MuscleMap"

  MuscleMapWidgetExtension:
    type: app-extension
    platform: iOS
    product: MuscleMapWidgetExtension
    sources:
      - path: MuscleMapWidget
        excludes:
          - "**/.DS_Store"
          - "**/Info.plist"
    entitlements:
      path: MuscleMapWidget/MuscleMapWidgetExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.buildinpublic.MuscleMap
    info:
      path: MuscleMapWidget/Info.plist
      properties:
        CFBundleDisplayName: "MuscleMap Widget"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.buildinpublic.MuscleMap.widget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"

  MuscleMapTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MuscleMapTests
        excludes:
          - "**/.DS_Store"
      - path: Resources
        buildPhase: resources
    dependencies:
      - target: MuscleMap
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.buildinpublic.MuscleMapTests
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: true
